name:                u
version:             0.1.0.0
github:              "githubuser/u"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/u#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Lib
  - Models
  - Common
  - PackageSpec
  dependencies:
  - typed-process
  - aeson
  - bytestring
  - time
  - directory
  - text
  - ghc
  - ghc-paths
  - mtl
  - jose
  - unix
  - beam-core
  - beam-postgres
  - time
  - random
  - resource-pool
  - cryptonite
  - microlens-platform
  - http-conduit
  - http-types
  - servant-auth
  - servant-auth-server
  - dhall
  - uuid
  - pretty-simple

executables:
  u-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - u
    - text
    - mtl
    - optparse-applicative

  server:
    main:                Server.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - u
    - text
    - mtl
    - optparse-applicative
    - beam-core
    - beam-postgres
    - postgresql-simple
    - bytestring
    - time
    - servant
    - servant-blaze
    - servant-server
    - blaze-html
    - wai
    - warp
    - resource-pool
    - aeson
    - cryptonite
    - microlens-platform
    - memory
    - bcrypt
    - servant-auth
    - servant-auth-server
    - servant-auth-client
    - jose
    - base64-bytestring
    - pretty-simple

tests:
  u-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - u
