name:                scarf
version:             0.1.0.0
github:              "aviaviavi/scarf"
license:             BSD3
author:              "Avi Press"
maintainer:          "mail@avi.press"
copyright:           "2019 Avi Press"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aviaviavi/scarf#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Scarf.Api
  - Scarf.Client
  - Scarf.Common
  - Scarf.Lib
  - Scarf.PackageSpec
  - Scarf.Types
  dependencies:
  - aeson
  - blaze-html
  - bytestring
  - Cabal
  - cryptonite
  - dhall
  - directory
  - ghc
  - ghc-paths
  - http-client
  - http-conduit
  - http-types
  - jose
  - microlens-platform
  - mtl
  - pretty-simple
  - random
  - resource-pool
  - safe-exceptions
  - semver
  - servant-auth
  - servant-auth-server
  - servant-blaze
  - servant-client
  - servant-client-core
  - servant-server
  - tar
  - text
  - time
  - time
  - typed-process
  - unix
  - uuid
  - warp
  - zlib

executables:
  scarf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-client
    - mtl
    - optparse-applicative
    - safe-exceptions
    - scarf
    - servant-client
    - text

tests:
  scarf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scarf
