name:                scarf
version:             0.6.0
github:              "aviaviavi/scarf"
license:             BSD3
author:              "Avi Press"
maintainer:          "avi@scarf.sh"
copyright:           "2019 Avi Press"

description:         Please see the README on GitHub at <https://github.com/aviaviavi/scarf#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Scarf.Api
  - Scarf.Client
  - Scarf.Common
  - Scarf.Lib
  - Scarf.PackageSpec
  - Scarf.Types
  dependencies:
  - aeson
  - aeson-pretty
  - blaze-html
  - bytestring
  - Cabal
  - cryptonite
  - directory
  - ghc
  - ghc-paths
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - jose
  - microlens-platform
  - mtl
  - pretty-simple
  - random
  - resource-pool
  - safe-exceptions
  - Cabal
  - servant-auth
  - servant-auth-server
  - servant-blaze
  - servant-client
  - servant-client-core
  - servant-server
  - tar
  - text
  - time
  - typed-process
  - unix
  - uuid
  - warp
  - zlib
  - process ==1.6.3.0
  - unordered-containers
  - yaml
  - hslogger
  - hspec
  - vector

executables:
  scarf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-client
    - mtl
    - optparse-applicative
    - http-client-tls
    - safe-exceptions
    - scarf
    - directory
    - servant-client
    - servant-client-core
    - text
    - hslogger

tests:
  scarf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scarf
    - hspec
    - time
    - Cabal
    - microlens-platform
